# Generated by Django 3.2.8 on 2023-01-18 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='abnormal_condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub', models.CharField(choices=[('Bates City', 'Bates City'), ('Burtville', 'Burtville'), ('Centerview', 'Centerview'), ('Chapel Hill', 'Chapel Hill'), ('Columbus', 'Columbus'), ('Concordia', 'Concordia'), ('Dover', 'Dover'), ('Fayetteville', 'Fayetteville'), ('Knob Noster', 'Knob Noster'), ('Levasy', 'Levasy'), ('Magnolia', 'Magnolia'), ('Montserrat', 'Montserrat'), ('Oak Grove', 'Oak Grove'), ('Odessa', 'Odessa'), ('Rose Hill', 'Rose Hill'), ('Tabo', 'Tabo')], max_length=12)),
                ('feeder', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_edited', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historicalabnormal_condition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Sub', models.CharField(choices=[('Bates City', 'Bates City'), ('Burtville', 'Burtville'), ('Centerview', 'Centerview'), ('Chapel Hill', 'Chapel Hill'), ('Columbus', 'Columbus'), ('Concordia', 'Concordia'), ('Dover', 'Dover'), ('Fayetteville', 'Fayetteville'), ('Knob Noster', 'Knob Noster'), ('Levasy', 'Levasy'), ('Magnolia', 'Magnolia'), ('Montserrat', 'Montserrat'), ('Oak Grove', 'Oak Grove'), ('Odessa', 'Odessa'), ('Rose Hill', 'Rose Hill'), ('Tabo', 'Tabo')], max_length=12)),
                ('feeder', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_edited', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical abnormal_condition',
                'verbose_name_plural': 'historical abnormal_conditions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
